### ISSUE TITLE
Improvement suggestion. 

### ISSUE THREAD

**Issue by Douglasproglima** [AbtzLabs/seed-php#7]
Add directory and message translation file

**Comment by rogeriotaques** [comment]
Hi @Douglasproglima, thanks for the pull request #6 . 

I could not get the point of having translation (locale) files of validations for Seed-PHP! The framework itself does not have built-in validation features and, if any, that would be implemented on a project basis. Can you give me your perspective on that?

**Comment by Douglasproglima** [comment]
I believe that the API endpoints will need to handle messages from GET, POST, PUT, and DELETE verbs, so it would be worth sending these messages to the frontend according to the application locale.

The idea is the same as the feature available in Laravel framework.

**Comment by rogeriotaques** [comment]
It sounds like a good idea, man. Thanks. I think, however, it can be implemented in a project-based instead of directly on Seed-PHP. The response codes themselves don't really need to be given with (localized) messages because each code already has its (very well documented) meaning.
